server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://imbank.cy9wmoq6sdhv.us-east-1.rds.amazonaws.com:3306/imbank
    username: admin
    password: '{cipher}70a64dc1d4123750a287d48225a23da38768c5d2d8a4debfa332e2c472cad9c9'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  servers:
    - url: http://localhost:8080/api/auth
      description: API Gateway
    - url: http://localhost:8081
      description: Direct Access

info:
  title: "Authentication Service API"
  description: "Handles user authentication, JWT tokens, and user management"
  version: "1.0.0"


jwt:
  secret: '{cipher}240c207930d6a771410c62d2b94c7c168e038ef0ed1aba378b6ed88a15bccebf0c6ca197be375c2ff23a003af56fad4267d1acc7739e9cb191fc6bb264c7e752739131753b53e760c8060768c506f6fc'
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
  issuer: imbank-auth-service